# Generated by Django 5.0.2 on 2024-06-14 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Uninfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='descricaocurso',
            field=models.TextField(default=' ', max_length=5000),
        ),
        migrations.AddField(
            model_name='curso',
            name='universidade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Uninfo.universidade'),
        ),
    ]
