# Generated by Django 5.0.2 on 2024-06-14 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Uninfo', '0002_curso_descricaocurso_curso_universidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='coordenador',
            field=models.CharField(default='Jan', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='curso',
            name='descricaocurso',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='curso',
            name='universidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Uninfo.universidade'),
        ),
    ]
