# Generated by Django 5.0.2 on 2024-06-28 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Uninfo', '0003_curso_coordenador_alter_curso_descricaocurso_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subrea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('Universidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Uninfo.universidade')),
                ('competicoes', models.ManyToManyField(related_name='equipes', to='Uninfo.competicao')),
                ('coordenadores', models.ManyToManyField(related_name='equipes_coordenadas', to='Uninfo.pessoa')),
                ('subareas', models.ManyToManyField(blank=True, related_name='equipes', to='Uninfo.subrea')),
            ],
        ),
    ]
